package ru.geekbrains.lesson;// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.testng.annotations.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;public class Test_2 {

  public static void main(String[] args) {
    WebDriver driver;
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();
    driver.get("https://crm.geekbrains.space/user/login");
    driver.manage().window().setSize(new Dimension(1900, 1022));
    driver.findElement(By.id("prependedInput")).sendKeys("Applanatest");
    driver.findElement(By.id("prependedInput2")).click();
    driver.findElement(By.id("prependedInput2")).sendKeys("Student2020!");
    driver.findElement(By.id("prependedInput2")).sendKeys(Keys.ENTER);
    {
      WebDriverWait wait = new WebDriverWait(driver, 3);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//li/a")));
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//li[contains(.,\'Панели инструментов/\')]"));
      assert (elements.size() > 0);
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".first > .unclickable > .title"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".first .last .title"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".first .last .title")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 3);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("(//a[contains(@href, \'/contact/create\')])[3]")));
    }
    {
      List<WebElement> elements = driver.findElements(By.linkText("Создать контактное лицо"));
      assert (elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".grid-toolbar"));
      assert (elements.size() > 0);
    }
    driver.findElement(By.linkText("Создать контактное лицо")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 3);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//h1[contains(.,\'Создать контактное лицо\')]")));
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//h1[contains(.,\'Создать контактное лицо\')]"));
      assert (elements.size() > 0);
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".select2-chosen"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("select2-drop-mask"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".lang-ru")).click();
    driver.findElement(By.cssSelector(".select2-input")).click();
    driver.findElement(By.cssSelector(".select2-input")).sendKeys(Keys.ENTER);
    driver.findElement(By.xpath("//div/div/div[2]/input")).click();
    driver.findElement(By.xpath("//div/div/div[2]/input")).sendKeys("Value");
    driver.findElement(By.xpath("//fieldset/div")).click();
    driver.findElement(By.xpath("//div[2]/div[2]/input")).click();
    driver.findElement(By.xpath("//div[2]/div[2]/input")).sendKeys("Value");
    driver.findElement(By.xpath("//div[2]/div[2]/div[2]/input")).click();
    driver.findElement(By.xpath("//div[2]/div[2]/div[2]/input")).sendKeys("Value");
    driver.findElement(By.cssSelector(".btn-group:nth-child(4) > .btn")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 3);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".message")));
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".message"));
      assert (elements.size() > 0);
    }
    driver.quit();
  }
}

